name: Pomodoro App CI/CD

on:
  push:
    branches:
      - main
#this is my job section
jobs:
  build-and-deploy:
    runs-on: [self-hosted, pomodgithubagent]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --no-cache -t pomo-app:${{ github.sha }} .

      - name: Stop and remove old container
        run: |
          docker stop pomo-app || true
          docker rm pomo-app || true

      - name: Run Docker container
        run: docker run -d --name pomo-app -p 5002:3000 pomo-app:${{ github.sha }}

      - name: Cleanup unused Docker images (optional)
        run: docker image prune -f
